[toolchain]
#IF option("riscv")
#IF option("stack-smashing-protection")
#+channel    = "nightly"
#ELSE
#REPLACE stable toolchain-name
channel    = "stable"
#ENDIF
components = ["rust-src"]
#REPLACE riscv32imac-unknown-none-elf rust_target
targets = ["riscv32imac-unknown-none-elf"]
#ELIF option("xtensa")
#REPLACE esp toolchain-name
#+channel = "esp"
#ENDIF
